#!/usr/bin/env python3
# Generated by adr-kit for ADR-NNN. Do not edit manually.
# Validates stdin against ADR-NNN enforcement rules.
# Usage: cat file.py | python validate.py
#        echo "suspicious line" | python validate.py
# Exit 0 = clean, exit 1 = violations found.
#
# This script is fully standalone — no adr-kit dependency required.
# Only the Python standard library (re, sys) is used.

import re
import sys

# Patterns are injected by adr-generate-scripts from the ADR's ## Enforcement block.
# Each entry is a compiled regex pattern and an error message.
FORBID_RULES = [
    (re.compile('\\bFoo\\b'), 'Do not use Foo.'),  # example — replaced at generation time
]


def main():
    lines = sys.stdin.readlines()
    violations = 0
    for i, line in enumerate(lines, 1):
        for pattern, message in FORBID_RULES:
            if pattern.search(line):
                print(f"VIOLATION line {i}: {message}", file=sys.stderr)
                print(f"  {line.rstrip()}", file=sys.stderr)
                violations += 1
    sys.exit(1 if violations > 0 else 0)


if __name__ == "__main__":
    main()
