// validate_adr_template.rs — reference template used by adr-generate-scripts.
//
// This file documents the shape of generated Rust validation scripts.
// It is NOT runnable as-is; {PLACEHOLDERS} are replaced by the generator.
// The generator in bin/adr-generate-scripts produces the actual Rust source.
//
// Generated script behaviour:
//   - Reads stdin line by line.
//   - Compiles every forbid_pattern / forbid_import rule from the ADR's
//     ## Enforcement block using the `regex` crate.
//   - Reports VIOLATION to stderr with line number, message, and snippet.
//   - Exit 0 = clean, exit 1 = at least one violation.
//
// Build requirements:
//   - Add `regex = "1"` to Cargo.toml dependencies.
//   - Build with: cargo build --release
//
// Example of a generated file for ADR-001 with one forbid rule:
//
//   // Generated by adr-kit for ADR-001. Do not edit manually.
//   use regex::Regex;
//   use std::io::{self, BufRead};
//
//   fn main() {
//       let patterns: Vec<(&str, &str)> = vec![
//           (r#"\bFoo\b"#, "Do not use Foo."),
//       ];
//
//       let compiled: Vec<(Regex, &str)> = patterns
//           .into_iter()
//           .map(|(p, m)| (Regex::new(p).unwrap_or_else(|e| panic!("invalid regex {:?}: {}", p, e)), m))
//           .collect();
//
//       let stdin = io::stdin();
//       let mut violations = 0usize;
//
//       for (i, line) in stdin.lock().lines().enumerate() {
//           let line = line.expect("read error");
//           for (re, msg) in &compiled {
//               if re.is_match(&line) {
//                   eprintln!("VIOLATION line {}: {}", i + 1, msg);
//                   eprintln!("  {}", line);
//                   violations += 1;
//               }
//           }
//       }
//
//       if violations > 0 {
//           std::process::exit(1);
//       }
//   }
//
// Template placeholders (replaced by generate_rust_script in bin/adr-generate-scripts):
//   {adr_id}      — e.g. "ADR-001"
//   {rules_block} — one line per rule: (r#"PATTERN"#, "MESSAGE"),
