#!/bin/bash
# validate_adr_template.sh — reference template used by adr-generate-scripts.
#
# This file documents the shape of generated shell validation scripts.
# It is NOT runnable as-is; {PLACEHOLDERS} are replaced by the generator.
# The generator in bin/adr-generate-scripts produces the actual shell script.
#
# Generated script behaviour:
#   - Reads stdin completely into memory (supports piping).
#   - Applies every forbid_pattern / forbid_import rule from the ADR's
#     ## Enforcement block via grep -E (POSIX extended regex).
#   - Reports VIOLATION to stderr with line number, message, and snippet.
#   - Exit 0 = clean, exit 1 = at least one violation.
#
# Example of a generated file for ADR-001 with one forbid rule:
#
#   #!/bin/bash
#   # Generated by adr-kit for ADR-001. Do not edit manually.
#   # Validates stdin against ADR-001 enforcement rules.
#   # Usage: cat file.py | bash validate.sh
#
#   set -euo pipefail
#
#   VIOLATIONS=0
#   INPUT=$(cat)
#
#   check_pattern() {
#       local pattern="$1"
#       local message="$2"
#       local line_num=0
#
#       while IFS= read -r line; do
#           line_num=$((line_num + 1))
#           if echo "$line" | grep -qE "$pattern" 2>/dev/null; then
#               echo "VIOLATION line $line_num: $message" >&2
#               echo "  $line" >&2
#               VIOLATIONS=$((VIOLATIONS + 1))
#           fi
#       done <<< "$INPUT"
#   }
#
#   check_pattern '\bFoo\b' 'Do not use Foo.'
#
#   [ "$VIOLATIONS" -gt 0 ] && exit 1
#   exit 0
#
# Template placeholders (replaced by generate_shell_script in bin/adr-generate-scripts):
#   {adr_id}       — e.g. "ADR-001"
#   {checks_block} — one line per rule: check_pattern 'PATTERN' 'MESSAGE'
