// validate_adr_template.go — reference template used by adr-generate-scripts.
//
// This file documents the shape of generated Go validation scripts.
// It is NOT runnable as-is; {PLACEHOLDERS} are replaced by the generator.
// The generator in bin/adr-generate-scripts produces the actual Go source.
//
// Generated script behaviour:
//   - Reads stdin line by line.
//   - Applies every forbid_pattern / forbid_import rule from the ADR's
//     ## Enforcement block as a compiled regexp.
//   - Reports VIOLATION to stderr with line number, message, and snippet.
//   - Exit 0 = clean, exit 1 = at least one violation, exit 2 = read error.
//
// Example of a generated file for ADR-001 with one forbid rule:
//
//   package main
//
//   import (
//       "bufio"
//       "fmt"
//       "os"
//       "regexp"
//   )
//
//   // Generated by adr-kit for ADR-001. Do not edit manually.
//   // Validates stdin against ADR-001 enforcement rules.
//
//   var forbidRules = []struct {
//       re      *regexp.Regexp
//       message string
//   }{
//       {regexp.MustCompile(`\bFoo\b`), "Do not use Foo."},
//   }
//
//   func main() {
//       scanner := bufio.NewScanner(os.Stdin)
//       var lines []string
//       for scanner.Scan() {
//           lines = append(lines, scanner.Text())
//       }
//       if err := scanner.Err(); err != nil {
//           fmt.Fprintf(os.Stderr, "read error: %v\n", err)
//           os.Exit(2)
//       }
//
//       violations := 0
//       for i, line := range lines {
//           for _, rule := range forbidRules {
//               if rule.re.MatchString(line) {
//                   fmt.Fprintf(os.Stderr, "VIOLATION line %d: %s\n  %s\n", i+1, rule.message, line)
//                   violations++
//               }
//           }
//       }
//
//       if violations > 0 {
//           os.Exit(1)
//       }
//   }
//
// Template placeholders (replaced by generate_go_script in bin/adr-generate-scripts):
//   {adr_id}      — e.g. "ADR-001"
//   {rules_block} — one line per rule: {regexp.MustCompile(`PATTERN`), "MESSAGE"},
