"""Shared model and bounded I/O primitives for client generation."""

from __future__ import annotations

import json
import os
import re
import threading
from dataclasses import dataclass
from pathlib import Path

CLIENT_IDS = ("claude-code-cli", "codex-cli", "github-copilot-cli")
WORKFLOW_IDS = (
    "adr",
    "audit",
    "context",
    "grill",
    "guardian",
    "init",
    "install-hooks",
    "judge",
    "lint",
    "migrate",
    "related",
    "retire",
    "review",
    "settings",
    "setup",
    "supersede",
    "upgrade",
)
GENERATED_CLIENTS = {"codex-cli": "codex", "github-copilot-cli": "copilot"}
COPY_ROOTS = ("bin", "schemas", "templates", "instructions")
COPY_EXCLUSIONS = {"bin/bump-version"}
HOOK_RUNTIME_FILES = (
    "hooks/run-hook.cmd",
    "hooks/adr-hook.py",
    "hooks/adr_hook_core.py",
    "hooks/adr_embed_query.py",
    "hooks/adr_pr_guard.py",
    # The guard derives its judge timeout from the declared runner budget, so
    # every client tree needs the declaration. Without it the mirrors silently
    # fall back to a constant, and the constant stops matching the moment
    # somebody changes the budget -- which is the drift this whole change is
    # about, reintroduced one directory over.
    "hooks/manifest.json",
    "hooks/adapters/__init__.py",
    "hooks/adapters/claude.py",
    "hooks/adapters/codex.py",
    "hooks/adapters/copilot.py",
    "hooks/bin/windows-x64/adr-hook.exe",
)
# The modules bin/ entrypoints import from OUTSIDE bin/. Mirrored at their own
# relative paths, because bin/adr-doctor resolves them by appending ROOT and
# ROOT/"scripts" to sys.path -- so the layout has to match, not just the files.
#
# COPY_ROOTS cannot carry these: declared_source_files() rglobs a whole root, so
# adding "scripts" would drag build-client-adapters.py into the mirrors and copy
# clients/workflows.json there too.
#
# That last file is why the exclusions below are load-bearing rather than
# tidiness. adr_doctor_models.generated_tree_owner() identifies a generated tree
# by the ABSENCE of clients/workflows.json -- it is the generator's input, and a
# canonical payload root always has it. Mirror it and the doctor stops degrading
# and starts hard-failing again, silently.
#
# Import closure verified: all eight are stdlib-only except
# clients/installer/__init__.py -> .contracts and detection.py -> .contracts,
# both of which are in the list. The two __init__.py files are one-line
# docstrings and are included so the static invariant test and the runtime
# importer agree; without them these would resolve only as implicit namespace
# packages.
RUNTIME_SUPPORT_FILES = (
    "clients/__init__.py",
    "clients/installer/__init__.py",
    "clients/installer/contracts.py",
    "clients/installer/detection.py",
    "hooks/__init__.py",
    "hooks/hook_benchmark.py",
    "scripts/adr_settings.py",
    "scripts/project_setup.py",
)
SOURCE_FILES = (
    "clients/capabilities.json",
    "clients/exceptions.json",
    "clients/workflows.json",
    "hooks/manifest.json",
    "packaging/dependencies-source.json",
    "packaging/executables-source.json",
    "packaging/public-artifacts.json",
    ".claude-plugin/plugin.json",
    ".claude-plugin/marketplace.json",
    ".mcp.json",
    ".agents/plugins/marketplace.json",
    "codex/.codex-plugin/plugin.json",
    ".github/plugin/marketplace.json",
    "copilot/plugin.json",
    "codex/.mcp.json",
    "copilot/.mcp.json",
)
PROVENANCE = "Generated by scripts/build-client-adapters.py from clients/workflows.json"
CACHE_VERSION = 1


class GenerationError(RuntimeError):
    """A deterministic input, validation, or drift failure."""


@dataclass
class Stats:
    files_read: int = 0
    bytes_read: int = 0
    files_written: int = 0
    bytes_written: int = 0
    unchanged: int = 0

    def as_dict(self) -> dict[str, int]:
        return {
            "files_read": self.files_read,
            "bytes_read": self.bytes_read,
            "files_written": self.files_written,
            "bytes_written": self.bytes_written,
            "unchanged": self.unchanged,
        }


def read(path: Path, stats: Stats) -> bytes:
    data = path.read_bytes()
    stats.files_read += 1
    stats.bytes_read += len(data)
    return data


def read_json(path: Path, stats: Stats) -> object:
    try:
        return json.loads(read(path, stats).decode("utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise GenerationError(f"invalid JSON: {path}: {exc}") from exc


def encoded_json(value: object) -> bytes:
    return (json.dumps(value, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def write(path: Path, content: bytes, mode: int | None, stats: Stats) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(
        f".{path.name}.{os.getpid()}.{threading.get_ident()}.tmp"
    )
    try:
        with temporary.open("xb") as stream:
            stream.write(content)
        if mode is not None:
            temporary.chmod(mode)
        os.replace(temporary, path)
    except BaseException:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass
        raise
    stats.files_written += 1
    stats.bytes_written += len(content)


def expected_version(root: Path, stats: Stats) -> str:
    text = read(root / "CHANGELOG.md", stats).decode("utf-8")
    match = re.search(r"^## \[(\d+\.\d+\.\d+)\]", text, re.MULTILINE)
    if not match:
        raise GenerationError("CHANGELOG.md has no stable release heading")
    return match.group(1)
